# Generated by Django 5.2.7 on 2025-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('kit', 'Kit Profesional'), ('individual', 'Individual')], default='kit', max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('deposito', models.DecimalField(decimal_places=2, default=20.0, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
