# Generated by Django 5.2.7 on 2025-10-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('teclado', 'TeclaFácil (solo)'), ('kit', 'TeclaFácil + mouse + audífonos (Kit Profesional)'), ('pilot', 'Programa Piloto (Empresa)')], default='kit', max_length=50),
        ),
    ]
